// SPDX-License-Identifier: MIT
package it.ratlab.manholes;

import net.neoforged.neoforge.common.ModConfigSpec;

/** Common config: {@code config/manholes-common.toml}. Read on the server; values can change on reload. */
public final class ManholesConfig {
    private static final ModConfigSpec.Builder B = new ModConfigSpec.Builder();

    static { B.push("general"); }
    public static final ModConfigSpec.BooleanValue UNBREAKABLE = B
            .comment("If true, world manholes (hatch, grate, cave_hole, city_manhole) cannot be broken in survival, so network nodes can't be moved.",
                    "If false they can be broken but drop nothing. Home manholes are always breakable.")
            .define("unbreakable", true);
    static { B.pop(); B.push("generation"); }
    public static final ModConfigSpec.BooleanValue NATURAL_SPAWN = B
            .comment("Run the mod's built-in spawn rules (data/manholes/manholes/builtin_spawn_rule/: villages and pillager outposts).",
                    "Set to false for packs that place manholes only through their own datapack rules, NBT structures or KubeJS.",
                    "Rules from datapacks (manholes/spawn_rule/) and KubeJS always apply, whatever this says.")
            .define("naturalSpawn", true);
    public static final ModConfigSpec.BooleanValue DISABLE_ALL_GENERATION = B
            .comment("Hard kill switch: no manhole is generated by any rule (datapack, built-in or KubeJS).")
            .define("disableAllGeneration", false);
    public static final ModConfigSpec.IntValue MIN_DISTANCE = B
            .comment("Default minimum distance in blocks between two generated manholes (a rule's own min_distance overrides it).")
            .defineInRange("minDistance", 192, 0, 100_000);
    public static final ModConfigSpec.IntValue PLACEMENT_ATTEMPTS = B
            .comment("Candidate spots tried inside a structure (or a chunk for scatter rules) before giving up.")
            .defineInRange("placementAttempts", 24, 1, 512);
    public static final ModConfigSpec.ConfigValue<java.util.List<? extends String>> STRUCTURE_BLACKLIST = B
            .comment("Structures (ids or #tags) no structure rule ever spawns around, whatever the rule says.",
                    "Applies to built-in, datapack and KubeJS rules.")
            .defineListAllowEmpty("structureBlacklist", java.util.List.of("#minecraft:mineshaft", "minecraft:stronghold",
                    "minecraft:ancient_city", "minecraft:trial_chambers", "minecraft:buried_treasure", "minecraft:monument",
                    "#minecraft:ocean_ruin", "#minecraft:shipwreck"), () -> "", ManholesConfig::validId);
    public static final ModConfigSpec.ConfigValue<java.util.List<? extends String>> BIOME_BLACKLIST = B
            .comment("Biomes (ids or #tags) where no manhole is generated by any rule (structure or scatter).")
            .defineListAllowEmpty("biomeBlacklist", java.util.List.of("#minecraft:is_ocean", "#minecraft:is_river"),
                    () -> "", ManholesConfig::validId);
    public static final ModConfigSpec.ConfigValue<java.util.List<? extends String>> DIMENSION_BLACKLIST = B
            .comment("Dimensions (ids) where no manhole is generated by any rule (structure or scatter).")
            .defineListAllowEmpty("dimensionBlacklist", java.util.List.of("minecraft:the_nether", "minecraft:the_end"),
                    () -> "", ManholesConfig::validId);
    static { B.pop(); B.push("home"); }
    public static final ModConfigSpec.BooleanValue HOME_ANYONE_CAN_BREAK = B
            .comment("If true, anyone can break a home manhole in survival. If false (default) only its owner can",
                    "(creative players and unowned homes always can).")
            .define("anyoneCanBreak", false);
    static { B.pop(); B.push("prying"); }
    public static final ModConfigSpec.EnumValue<Difficulty> DIFFICULTY = B
            .comment("How prying works.",
                    " simple: hold right-click for pryTicks (the 1.0 behaviour; no phases, no mashing, no rust).",
                    " normal: phases INSERT (hold) -> LEVER (mash the key) -> SLIDE (hold). Preset:",
                    "         insertTicks 20, slideTicks 30, mashPerPress 6, mashDecayPerTick 0.8",
                    " hard:   insertTicks 30, slideTicks 40, mashPerPress 4.5, mashDecayPerTick 1.0",
                    " custom: reads insertTicks, slideTicks, mashPerPress and mashDecayPerTick below.",
                    "noiseRadius, the other mash* keys, the slip keys and the rust keys apply to normal, hard and custom.")
            .defineEnum("difficulty", Difficulty.NORMAL);
    public static final ModConfigSpec.BooleanValue MATCH_ANY_CROWBAR = B
            .comment("If true, any item whose registry path contains 'crowbar' (e.g. somemod:rusty_crowbar) also pries",
                    "manholes open, on top of the #manholes:pry_tools item tag. Only manholes:crowbar gets the custom prying pose.")
            .define("matchAnyCrowbar", true);
    public static final ModConfigSpec.IntValue PRY_TICKS = B
            .comment("simple mode only: ticks of holding right-click needed to pry a manhole open (20 ticks = 1 second).")
            .defineInRange("pryTicks", 60, 1, 12_000);
    public static final ModConfigSpec.IntValue NOISE_RADIUS = B
            .comment("Radius in blocks in which mobs from #manholes:attracted_by_noise are alerted while prying.")
            .defineInRange("noiseRadius", 24, 0, 256);
    public static final ModConfigSpec.IntValue INSERT_TICKS = B
            .comment("custom: ticks of the INSERT phase (wedging the crowbar in; hold right-click).")
            .defineInRange("insertTicks", 20, 1, 12_000);
    public static final ModConfigSpec.IntValue SLIDE_TICKS = B
            .comment("custom: ticks of the SLIDE phase (dragging the cover aside; hold right-click).")
            .defineInRange("slideTicks", 30, 1, 12_000);
    public static final ModConfigSpec.DoubleValue MASH_PER_PRESS = B
            .comment("custom: percent of the LEVER bar each accepted press of the mash key adds (rust divides it by",
                    "1 + rustMultiplier * rust).")
            .defineInRange("mashPerPress", 6.0, 0.1, 100.0);
    public static final ModConfigSpec.DoubleValue MASH_DECAY_PER_TICK = B
            .comment("custom: percent of the LEVER bar lost every tick without a press (never below 0).")
            .defineInRange("mashDecayPerTick", 0.8, 0.0, 100.0);
    public static final ModConfigSpec.IntValue MASH_MAX_PRESSES_PER_SECOND = B
            .comment("Anti-autoclicker: presses the server accepts in any 20-tick window; extra presses are ignored.")
            .defineInRange("mashMaxPressesPerSecond", 12, 1, 20);
    public static final ModConfigSpec.IntValue MASH_NOISE_EVERY = B
            .comment("Every N accepted presses the lever clanks and alerts the undead within noiseRadius.")
            .defineInRange("mashNoiseEvery", 5, 1, 1000);
    public static final ModConfigSpec.DoubleValue MASH_GIVE_UP_THRESHOLD = B
            .comment("If the LEVER bar reached this percent and then decays back to 0, the attempt ends with",
                    "'The crowbar slips.' (the use key must be released before trying again). 100 = never.")
            .defineInRange("mashGiveUpThreshold", 30.0, 0.0, 100.0);
    public static final ModConfigSpec.DoubleValue FAIL_NOISE_MULTIPLIER = B
            .comment("A slip alerts mobs within noiseRadius * this.")
            .defineInRange("failNoiseMultiplier", 2.0, 0.0, 16.0);
    public static final ModConfigSpec.IntValue FAIL_DURABILITY_COST = B
            .comment("Extra durability the pry tool loses when it slips.")
            .defineInRange("failDurabilityCost", 3, 0, 10_000);
    public static final ModConfigSpec.BooleanValue RUST_ENABLED = B
            .comment("Each world manhole has a rust level 0-3 (derived from its node id, stored in its block entity as",
                    "'rust' so NBT can override it). Home manholes are always 0. Not used in simple mode.")
            .define("rustEnabled", true);
    public static final ModConfigSpec.DoubleValue RUST_MULTIPLIER = B
            .comment("Insert / slide durations are multiplied by (1 + rustMultiplier * rust), mashPerPress is divided by it.")
            .defineInRange("rustMultiplier", 0.25, 0.0, 10.0);
    static { B.pop(); B.push("travel"); }
    public static final ModConfigSpec.BooleanValue ALLOW_CROSS_DIMENSION = B
            .comment("Allow travelling to nodes in another dimension.")
            .define("allowCrossDimension", false);
    public static final ModConfigSpec.IntValue TRAVEL_FADE_TICKS = B
            .comment("Length of the fade to black before arriving. The player is invulnerable and immobile meanwhile.")
            .defineInRange("travelFadeTicks", 40, 1, 1200);
    public static final ModConfigSpec.IntValue TIME_COST_PER_KM = B
            .comment("World time advanced per km travelled (minimum 1 km). Only applied when exactly one player is online.")
            .defineInRange("timeCostPerKm", 1000, 0, 24_000);
    public static final ModConfigSpec.DoubleValue HUNGER_COST_PER_KM = B
            .comment("Food exhaustion added per km travelled (minimum 1 km). 4 exhaustion = 1 hunger point.")
            .defineInRange("hungerCostPerKm", 2.0, 0.0, 40.0);
    public static final ModConfigSpec.ConfigValue<String> EXTRA_ITEM_COST = B
            .comment("Optional item consumed per trip: an item id ('minecraft:torch') or an item tag ('#c:foods'). Empty = none.")
            .define("extraItemCost", "");
    public static final ModConfigSpec.IntValue EXTRA_ITEM_COST_COUNT = B
            .comment("How many of extraItemCost are consumed per trip.")
            .defineInRange("extraItemCostCount", 1, 0, 64 * 36);
    public static final ModConfigSpec.DoubleValue AMBUSH_CHANCE = B
            .comment("Chance of an ambush on arrival. Mobs come from #manholes:ambush_mobs (empty by default = no ambush).")
            .defineInRange("ambushChance", 0.1, 0.0, 1.0);
    public static final ModConfigSpec.IntValue AMBUSH_COUNT_MIN = B
            .defineInRange("ambushCountMin", 1, 0, 32);
    public static final ModConfigSpec.IntValue AMBUSH_COUNT_MAX = B
            .defineInRange("ambushCountMax", 2, 0, 32);
    public static final ModConfigSpec.BooleanValue AMBUSH_AT_HOME = B
            .comment("Ambushes can also happen when arriving at a home manhole (false = home is safe).")
            .define("ambushAtHome", false);
    public static final ModConfigSpec.IntValue COMBAT_COOLDOWN_TICKS = B
            .comment("A player who took damage in the last N ticks is 'in combat' and can't travel.")
            .defineInRange("combatCooldownTicks", 100, 0, 12_000);
    public static final ModConfigSpec.IntValue TRAVEL_COOLDOWN_TICKS = B
            .comment("Cooldown per player between two trips.")
            .defineInRange("travelCooldownTicks", 100, 0, 72_000);
    public static final ModConfigSpec.BooleanValue ANIMATION_ENABLED = B
            .comment("Climb-down / climb-up animation around the fade. false = the plain fade of 1.0.")
            .define("animationEnabled", true);
    public static final ModConfigSpec.IntValue DESCENT_TICKS = B
            .comment("Length of the climb down: step onto the cover (1/4), look down, climb ~1.5 blocks down (rest).",
                    "The fade to black runs during the climb; the teleport happens when it ends.")
            .defineInRange("descentTicks", 40, 12, 1200);
    public static final ModConfigSpec.IntValue ASCENT_TICKS = B
            .comment("Length of the climb up at the destination: rise ~1.5 blocks (2/3), step off and level the head (1/3).")
            .defineInRange("ascentTicks", 30, 12, 1200);
    static { B.pop(); B.push("recipes"); }
    public static final ModConfigSpec.BooleanValue ENABLE_DEFAULT_RECIPES = B
            .comment("Load the mod's default recipes (crowbar, home manhole; vanilla items only). They use the NeoForge",
                    "condition 'manholes:default_recipes_enabled', read when datapacks load (/reload after a change).",
                    "Datapacks and KubeJS can still replace or remove them by id.")
            .define("enableDefaultRecipes", true);
    static { B.pop(); }

    public static final ModConfigSpec SPEC = B.build();

    private static boolean validId(Object o) {
        if (!(o instanceof String str)) {
            return false;
        }
        String id = str.startsWith("#") ? str.substring(1) : str;
        return net.minecraft.resources.ResourceLocation.tryParse(id) != null;
    }

    /** A string-list value, or its default before the config is loaded. */
    @SuppressWarnings("unchecked")
    public static java.util.List<String> list(ModConfigSpec.ConfigValue<java.util.List<? extends String>> v) {
        return (java.util.List<String>) (SPEC.isLoaded() ? v.get() : v.getDefault());
    }

    private ManholesConfig() {}

    public enum Difficulty { SIMPLE, NORMAL, HARD, CUSTOM }

    public static <E extends Enum<E>> E e(ModConfigSpec.EnumValue<E> v) {
        return SPEC.isLoaded() ? v.get() : v.getDefault();
    }

    public static boolean isLoaded() {
        return SPEC.isLoaded();
    }

    public static int i(ModConfigSpec.IntValue v) {
        return SPEC.isLoaded() ? v.getAsInt() : v.getDefault();
    }

    public static double d(ModConfigSpec.DoubleValue v) {
        return SPEC.isLoaded() ? v.getAsDouble() : v.getDefault();
    }

    public static boolean b(ModConfigSpec.BooleanValue v) {
        return SPEC.isLoaded() ? v.getAsBoolean() : v.getDefault();
    }

    public static String s(ModConfigSpec.ConfigValue<String> v) {
        return SPEC.isLoaded() ? v.get() : v.getDefault();
    }
}
