"""Extra travel-point looks for datapack variants (24x24 px footprint like the manhole, hitbox 1x1).
All textures are VANILLA, so the variants match the game (and follow the player's resource pack).

  hatch  - spruce trapdoor in a stripped-log frame, iron hinges; open: lid propped up 45 deg, ladder top
           poking out of the pit.
  grate  - dark iron drain grate (anvil texture) in a stone-brick frame; open: grate hinged up 45 deg.
  cave   - ring of cobblestone / mossy cobble / tuff / andesite rocks around a dark pit, boulders on top;
           open: boulders rolled aside.

Run from the project root:  python art/make_variants.py   (writes models/block/variant_*.json)
UVs follow vanilla conventions (1 texel per model px, wrapped into 0..16, never stretched), long pieces
are split at 16 px, and no two elements share a same-facing coplanar face (no z-fighting).
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import make_assets as A  # noqa: E402

TEX = {
    "log": "minecraft:block/stripped_spruce_log",
    "planks": "minecraft:block/spruce_planks",
    "trapdoor": "minecraft:block/spruce_trapdoor",
    "iron": "minecraft:block/anvil",
    "tiles": "minecraft:block/stone_bricks",   # lighter than the anvil-iron bars: readable contrast
    "pit": "minecraft:block/black_concrete_powder",
    "pit_rim": "minecraft:block/coarse_dirt",
    "ladder": "minecraft:block/ladder",
    "cobble": "minecraft:block/cobblestone",
    "mossy": "minecraft:block/mossy_cobblestone",
    "tuff": "minecraft:block/tuff",
    "andesite": "minecraft:block/andesite",
    "stone": "minecraft:block/stone",
}


def _span(a, b):
    """Map model coords a..b to a 0..16 texture range without stretching (wrap like vanilla tiling)."""
    w = b - a
    if w >= 16:
        return 0.0, 16.0
    s = a % 16
    if s + w > 16:
        s = 16 - w
    return round(s, 3), round(s + w, 3)


def box(name, frm, to, tex, rot=None, faces=None, top=None):
    """Element with vanilla-style uvs. tex: texture var for the sides; top: optional var for up/down."""
    (x0, y0, z0), (x1, y1, z1) = frm, to
    ux, uz = _span(x0, x1), _span(z0, z1)
    v0, v1 = _span(16 - y1, 16 - y0)
    f = {
        "up": {"uv": [ux[0], uz[0], ux[1], uz[1]], "texture": top or tex},
        "down": {"uv": [ux[0], uz[0], ux[1], uz[1]], "texture": top or tex},
        "north": {"uv": [ux[0], v0, ux[1], v1], "texture": tex},
        "south": {"uv": [ux[0], v0, ux[1], v1], "texture": tex},
        "west": {"uv": [uz[0], v0, uz[1], v1], "texture": tex},
        "east": {"uv": [uz[0], v0, uz[1], v1], "texture": tex},
    }
    if faces is not None:
        f = {k: v for k, v in f.items() if k in faces}
    e = {"name": name, "from": list(frm), "to": list(to), "faces": f}
    if rot:
        e["rotation"] = rot
    return e


def split_x(name, x0, x1, y0, y1, z0, z1, tex, top=None):
    """Split a bar longer than 16 px at x=8 so its texture never stretches."""
    if x1 - x0 <= 16:
        return [box(name, (x0, y0, z0), (x1, y1, z1), tex, top=top)]
    m = (x0 + x1) / 2   # split at the bar's own middle (a fixed x=8 inverts pieces of shifted bars)
    return [box(name + "_a", (x0, y0, z0), (m, y1, z1), tex, top=top),
            box(name + "_b", (m, y0, z0), (x1, y1, z1), tex, top=top)]


def split_z(name, x0, x1, y0, y1, z0, z1, tex, top=None):
    if z1 - z0 <= 16:
        return [box(name, (x0, y0, z0), (x1, y1, z1), tex, top=top)]
    m = (z0 + z1) / 2
    return [box(name + "_a", (x0, y0, z0), (x1, y1, m), tex, top=top),
            box(name + "_b", (x0, y0, m), (x1, y1, z1), tex, top=top)]


def pit(rim=True):
    """Dark pit filling the opening (-1..17), with a thin coarse-dirt lip to fake depth."""
    els = [box("pit", (-1, 0.02, -1), (17, 0.04, 17), "#pit", faces=("up",))]
    if rim:
        els += [
            box("lip_n", (-1, 0.04, -1), (17, 0.3, 0), "#pit_rim", faces=("up", "south")),
            box("lip_s", (-1, 0.04, 16), (17, 0.3, 17), "#pit_rim", faces=("up", "north")),
            box("lip_w", (-1, 0.05, 0), (0, 0.28, 16), "#pit_rim", faces=("up", "east")),
            box("lip_e", (16, 0.05, 0), (17, 0.28, 16), "#pit_rim", faces=("up", "west")),
        ]
    return els


def model(textures, els, cutout=False):
    m = {"credit": "Manhole Travel - generated by art/make_variants.py", "ambientocclusion": False,
         "textures": textures, "elements": els, "display": A.DISPLAY_BLOCK}
    if cutout:
        m["render_type"] = "minecraft:cutout"
    return m


def tex(*keys, particle):
    t = {k: TEX[k] for k in keys}
    t["particle"] = TEX[particle]
    return t


# ---------------------------------------------------------------- hatch
def log_frame():
    # N/S beams full length (split at 16), W/E beams between them with slightly lower tops (never coplanar)
    return (split_x("frame_n", -4, 20, 0, 2, -4, -1, "#log")
            + split_x("frame_s", -4, 20, 0, 2, 17, 20, "#log")
            + split_z("frame_w", -4, -1, 0, 1.9, -1, 17, "#log")
            + split_z("frame_e", 17, 20, 0, 1.9, -1, 17, "#log"))


def hatch_lid(rot=None):
    # top uses the trapdoor texture (cutout): its gaps show the dark pit below
    els = [box("lid_a", (-1, 0.5, -1), (8, 1.75, 17), "#planks", rot, top="#trapdoor"),
           box("lid_b", (8, 0.5, -1), (16.8, 1.75, 17), "#planks", rot, top="#trapdoor")]  # 0.2 px short: clears the far beam while swinging
    for i, z0 in enumerate((1, 13)):          # iron hinge straps from the west (hinge) edge
        els.append(box(f"strap_{i}", (-0.6, 1.75, z0), (10, 2.0, z0 + 2), "#iron", rot))  # runs into its knuckle
    els.append(box("handle", (13, 1.75, 7), (15, 2.2, 9), "#iron", rot))
    return els


def hatch_models():
    t = tex("log", "planks", "trapdoor", "iron", "pit", "pit_rim", "ladder", particle="planks")
    closed = model(t, log_frame() + pit(rim=False) + hatch_lid(), cutout=True)
    ladder = box("ladder_top", (3, -1, 0.1), (13, 4, 0.6), "#ladder", faces=("south", "north"))
    opened = model(t, log_frame() + pit() + [ladder]
                   + hatch_lid({"angle": 45, "axis": "z", "origin": [-1, 1.75, 8]}), cutout=True)
    return closed, opened


# ---------------------------------------------------------------- grate
def tile_frame():
    return (split_x("frame_n", -4, 20, 0, 1.0, -4, -1, "#tiles")
            + split_x("frame_s", -4, 20, 0, 1.0, 17, 20, "#tiles")
            + split_z("frame_w", -4, -1, 0, 0.9, -1, 17, "#tiles")
            + split_z("frame_e", 17, 20, 0, 0.9, -1, 17, "#tiles"))


GRATE_BARS = 6
GRATE_BAR_W = 1.4


def grate_bars(y=0.3, rot=None):
    """Evenly spaced bars across the 18 px opening (-1..17), same gap at both walls, one piece each
    (no split seams), plus two cross bars resting on top. Bars end exactly at the frame's inner edge."""
    gap = (18 - GRATE_BARS * GRATE_BAR_W) / (GRATE_BARS + 1)
    els = []
    for i in range(GRATE_BARS):
        x0 = round(-1 + gap + i * (GRATE_BAR_W + gap), 3)
        els.append(box(f"bar_{i}", (x0, y, -0.8), (round(x0 + GRATE_BAR_W, 3), y + 1.0, 17), "#iron",
                       rot))
    for n, z in (("cross_a", 4), ("cross_b", 10.5)):
        els.append(box(n, (-1, y + 1.0, z), (17, y + 1.3, z + 1.5), "#iron", rot))
    return els


def grate_models():
    t = tex("tiles", "iron", "pit", particle="tiles")
    closed = model(t, tile_frame() + pit(rim=False) + grate_bars())
    # open: hinged on the south edge, north side lifted and propped up 45 deg over the pit
    opened = model(t, tile_frame() + pit(rim=False)
                   + grate_bars(y=0.3, rot={"angle": 45, "axis": "x", "origin": [8, 0.3, 17]}))
    return closed, opened


# ---------------------------------------------------------------- cave
ROCKS = [  # (x0, z0, x1, z1, height, texture): ring around the pit, all heights distinct
    (-4, -4, 3, 2, 3.0, "#cobble"), (3, -4, 11, -1, 2.2, "#mossy"), (11, -4, 20, 1, 3.6, "#tuff"),
    (16, 1, 20, 9, 2.6, "#andesite"), (15, 9, 20, 20, 3.3, "#cobble"), (6, 17, 15, 20, 2.0, "#mossy"),
    (-4, 14, 6, 20, 2.9, "#tuff"), (-4, 2, -1, 14, 2.4, "#mossy"),
]


def cave_models():
    t = tex("cobble", "mossy", "tuff", "andesite", "stone", "pit", "pit_rim", particle="cobble")
    ring = [box(f"rock_{i}", (x0, 0, z0), (x1, h, z1), tx) for i, (x0, z0, x1, z1, h, tx) in enumerate(ROCKS)]
    closed_b = [
        box("boulder_a", (0, 0.05, 1), (9, 4.5, 9), "#stone"),
        box("boulder_b", (7, 0.1, 6), (15, 3.7, 15), "#andesite",
            {"angle": 22.5, "axis": "y", "origin": [11, 0, 10]}),
        box("boulder_c", (1, 0.2, 9), (7, 2.8, 15), "#mossy"),
    ]
    open_b = [
        box("boulder_a", (12, 3.4, 11.5), (19.5, 7.0, 19), "#stone"),
        box("boulder_c", (-3, 3.0, 15), (3, 5.2, 19.5), "#mossy"),
    ]
    return model(t, ring + pit(rim=False) + closed_b), model(t, ring + pit(rim=False) + open_b)


def main():
    for name, fn in [("hatch", hatch_models), ("grate", grate_models), ("cave", cave_models)]:
        closed, opened = fn()
        A.save_json(closed, f"block/variant_{name}.json")
        A.save_json(opened, f"block/variant_{name}_open.json")
    # the old procedural variant textures are no longer used
    tdir = os.path.join(A.ROOT, "textures", "block")
    for f in ("variant_wood", "variant_stone", "variant_iron", "variant_hole_dirt", "variant_hole_cave"):
        path = os.path.join(tdir, f + ".png")
        if os.path.exists(path):
            os.remove(path)
    print("done")


if __name__ == "__main__":
    main()
